[2025-01-16T19:55:57.567+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-16T19:34:14.698350+00:00 [queued]>
[2025-01-16T19:55:57.620+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-16T19:34:14.698350+00:00 [queued]>
[2025-01-16T19:55:57.622+0000] {taskinstance.py:1361} INFO - Starting attempt 10 of 10
[2025-01-16T19:55:57.699+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-16 19:34:14.698350+00:00
[2025-01-16T19:55:57.727+0000] {standard_task_runner.py:57} INFO - Started process 302 to run task
[2025-01-16T19:55:57.742+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'extract_data', 'manual__2025-01-16T19:34:14.698350+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpzpoau1ou']
[2025-01-16T19:55:57.753+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask extract_data
[2025-01-16T19:55:58.033+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-16T19:34:14.698350+00:00 [running]> on host a2a216e8ef88
[2025-01-16T19:55:58.398+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T19:34:14.698350+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T19:34:14.698350+00:00'
[2025-01-16T19:55:58.483+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-16T19:55:58.629+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-16T19:55:58.652+0000] {db_to_xls.py:28} INFO - Extracted Users and saved to /tmp/Users.csv.
[2025-01-16T19:55:58.706+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-16T19:55:58.785+0000] {db_to_xls.py:28} INFO - Extracted Transactions and saved to /tmp/Transactions.csv.
[2025-01-16T19:55:58.807+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-16T19:55:58.887+0000] {db_to_xls.py:28} INFO - Extracted Membership_Purchases and saved to /tmp/Membership_Purchases.csv.
[2025-01-16T19:55:58.952+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-16T19:55:58.984+0000] {db_to_xls.py:28} INFO - Extracted MDR_Data and saved to /tmp/MDR_Data.csv.
[2025-01-16T19:55:59.035+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-16T19:55:59.069+0000] {db_to_xls.py:28} INFO - Extracted User_Activity and saved to /tmp/User_Activity.csv.
[2025-01-16T19:55:59.099+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-16T19:55:59.156+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_process_with_excel_report, task_id=extract_data, execution_date=20250116T193414, start_date=20250116T195557, end_date=20250116T195559
[2025-01-16T19:55:59.297+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-16T19:55:59.422+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
