[2025-01-17T17:32:34.081+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data manual__2025-01-17T17:24:34.119787+00:00 [queued]>
[2025-01-17T17:32:34.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data manual__2025-01-17T17:24:34.119787+00:00 [queued]>
[2025-01-17T17:32:34.091+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2025-01-17T17:32:34.105+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-17 17:24:34.119787+00:00
[2025-01-17T17:32:34.131+0000] {standard_task_runner.py:57} INFO - Started process 363 to run task
[2025-01-17T17:32:34.138+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'load_data', 'manual__2025-01-17T17:24:34.119787+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmp52qnnep5']
[2025-01-17T17:32:34.144+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask load_data
[2025-01-17T17:32:34.237+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.load_data manual__2025-01-17T17:24:34.119787+00:00 [running]> on host e075edadbc7d
[2025-01-17T17:32:34.434+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T17:24:34.119787+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T17:24:34.119787+00:00'
[2025-01-17T17:32:34.739+0000] {db_to_xls.py:147} INFO - Loaded /tmp/user_profiling.csv with 14 rows and 9 columns.
[2025-01-17T17:32:34.754+0000] {db_to_xls.py:147} INFO - Loaded /tmp/transaction_totals_per_type.csv with 10 rows and 4 columns.
[2025-01-17T17:32:34.767+0000] {db_to_xls.py:147} INFO - Loaded /tmp/daily_activity_report.csv with 6 rows and 3 columns.
[2025-01-17T17:32:34.825+0000] {db_to_xls.py:147} INFO - Loaded /tmp/transactions_with_mdr_df.csv with 14 rows and 15 columns.
[2025-01-17T17:32:34.938+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.048+0000] {sql.py:418} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS sprout.user_profiling (
                    user_id INT,
                    name TEXT,
                    timestamp TIMESTAMP,
                    membership_type TEXT,
                    membership_purchase_status TEXT,
                    mdr_percentage FLOAT,
                    first_transaction TIMESTAMP,
                    invoice_total_count INT,
                    invoice_total_amount FLOAT
                );
            , parameters: None
[2025-01-17T17:32:35.163+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.190+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE sprout.user_profiling;, parameters: None
[2025-01-17T17:32:35.247+0000] {db_to_xls.py:213} INFO - Table sprout.user_profiling truncated.
[2025-01-17T17:32:35.273+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.293+0000] {sql.py:418} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS sprout.transaction_totals_per_type (
                    timestamp TIMESTAMP,
                    membership_type TEXT,
                    invoice_total_count INT,
                    invoice_total_amount FLOAT
                );
            , parameters: None
[2025-01-17T17:32:35.306+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.320+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE sprout.transaction_totals_per_type;, parameters: None
[2025-01-17T17:32:35.326+0000] {db_to_xls.py:213} INFO - Table sprout.transaction_totals_per_type truncated.
[2025-01-17T17:32:35.337+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.350+0000] {sql.py:418} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS sprout.daily_activity_report (
                    timestamp TIMESTAMP,
                    invoice_total_count INT,
                    invoice_total_amount FLOAT
                );
            , parameters: None
[2025-01-17T17:32:35.363+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.374+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE sprout.daily_activity_report;, parameters: None
[2025-01-17T17:32:35.423+0000] {db_to_xls.py:213} INFO - Table sprout.daily_activity_report truncated.
[2025-01-17T17:32:35.451+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.522+0000] {sql.py:418} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS sprout.transactions_with_mdr (
                    transaction_id INT,
                    user_id INT,
                    transaction_amount FLOAT,
                    timestamp TIMESTAMP,
                    name TEXT,
                    email TEXT,
                    phone TEXT,
                    membership_id FLOAT,
                    membership_type TEXT,
                    purchase_date DATE,
                    expiry_date DATE,
                    mdr_id FLOAT,
                    mdr_percentage FLOAT,
                    membership_purchase_status TEXT,
                    effective_amount FLOAT
                );
            , parameters: None
[2025-01-17T17:32:35.586+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.646+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE sprout.transactions_with_mdr;, parameters: None
[2025-01-17T17:32:35.664+0000] {db_to_xls.py:213} INFO - Table sprout.transactions_with_mdr truncated.
[2025-01-17T17:32:35.688+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:35.845+0000] {sql.py:515} INFO - Done loading. Loaded a total of 14 rows into sprout.user_profiling
[2025-01-17T17:32:35.847+0000] {db_to_xls.py:222} INFO - Inserted 14 rows into sprout.user_profiling.
[2025-01-17T17:32:35.915+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:36.008+0000] {sql.py:515} INFO - Done loading. Loaded a total of 10 rows into sprout.transaction_totals_per_type
[2025-01-17T17:32:36.009+0000] {db_to_xls.py:222} INFO - Inserted 10 rows into sprout.transaction_totals_per_type.
[2025-01-17T17:32:36.069+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:36.151+0000] {sql.py:515} INFO - Done loading. Loaded a total of 6 rows into sprout.daily_activity_report
[2025-01-17T17:32:36.191+0000] {db_to_xls.py:222} INFO - Inserted 6 rows into sprout.daily_activity_report.
[2025-01-17T17:32:36.229+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:32:36.348+0000] {db_to_xls.py:232} ERROR - Error during data loading: can't adapt type 'NAType'
[2025-01-17T17:32:36.350+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/db_to_xls.py", line 227, in load_data
    insert_data(transactions_with_mdr, 'sprout.transactions_with_mdr')
  File "/opt/airflow/dags/db_to_xls.py", line 217, in insert_data
    postgres_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 509, in insert_rows
    cur.execute(sql, values)
psycopg2.ProgrammingError: can't adapt type 'NAType'
[2025-01-17T17:32:36.371+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=load_data, execution_date=20250117T172434, start_date=20250117T173234, end_date=20250117T173236
[2025-01-17T17:32:36.389+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task load_data (can't adapt type 'NAType'; 363)
[2025-01-17T17:32:36.714+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T17:32:36.905+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
