[2025-01-17T17:21:29.289+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-17T17:21:16.037120+00:00 [queued]>
[2025-01-17T17:21:29.309+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-17T17:21:16.037120+00:00 [queued]>
[2025-01-17T17:21:29.358+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-17T17:21:29.406+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-17 17:21:16.037120+00:00
[2025-01-17T17:21:29.523+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2025-01-17T17:21:29.594+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'extract_data', 'manual__2025-01-17T17:21:16.037120+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpwjk_ucp0']
[2025-01-17T17:21:29.611+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask extract_data
[2025-01-17T17:21:29.974+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-17T17:21:16.037120+00:00 [running]> on host e075edadbc7d
[2025-01-17T17:21:30.549+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T17:21:16.037120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T17:21:16.037120+00:00'
[2025-01-17T17:21:30.828+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:21:31.561+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-17T17:21:31.694+0000] {db_to_xls.py:29} INFO - Extracted Users and saved to /tmp/Users.csv.
[2025-01-17T17:21:31.797+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:21:31.861+0000] {db_to_xls.py:29} INFO - Extracted Transactions and saved to /tmp/Transactions.csv.
[2025-01-17T17:21:31.982+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:21:32.026+0000] {db_to_xls.py:29} INFO - Extracted Membership_Purchases and saved to /tmp/Membership_Purchases.csv.
[2025-01-17T17:21:32.103+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:21:32.177+0000] {db_to_xls.py:29} INFO - Extracted MDR_Data and saved to /tmp/MDR_Data.csv.
[2025-01-17T17:21:32.343+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:21:32.388+0000] {db_to_xls.py:29} INFO - Extracted User_Activity and saved to /tmp/User_Activity.csv.
[2025-01-17T17:21:32.571+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-17T17:21:32.688+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_process_with_excel_report, task_id=extract_data, execution_date=20250117T172116, start_date=20250117T172129, end_date=20250117T172132
[2025-01-17T17:21:33.028+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-17T17:21:33.124+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
